//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NavalBaseEntities2 : DbContext
    {
        private static NavalBaseEntities2 _context;

        public static NavalBaseEntities2 GetContext()
        {
            if (_context == null)
                _context = new NavalBaseEntities2();
            return _context;
        }

        public NavalBaseEntities2()
            : base("name=NavalBaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Базы> Базы { get; set; }
        public virtual DbSet<Корабли> Корабли { get; set; }
        public virtual DbSet<Личный_состав> Личный_состав { get; set; }
        public virtual DbSet<Учения> Учения { get; set; }
        public virtual DbSet<Части> Части { get; set; }
    }
}
