//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корабли
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Корабли()
        {
            this.Учения = new HashSet<Учения>();
        }
    
        public int Идентификационный_номер_корабля { get; set; }
        public string Название_корабля { get; set; }
        public string Тип_корабля { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public int Наработка { get; set; }
        public int Количество_посадочных_мест { get; set; }
        public string Устройство_двигателя { get; set; }
        public string Тип_привода { get; set; }
        public string Размещение_корпуса { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учения> Учения { get; set; }
    }
}
