//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Личный_состав
    {
        public int Номер_солдата { get; set; }
        public string Фамилия { get; set; }
        public int Часть { get; set; }
        public string Должность { get; set; }
        public int Год_рождения { get; set; }
        public int Год_поступления_на_службу { get; set; }
        public Nullable<int> Выслуга_лет { get; set; }
        public string Награды { get; set; }
        public string Фото { get; set; }
    
        public virtual Части Части { get; set; }
    }
}
