//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учения
    {
        public int Номер_учения { get; set; }
        public int Часть { get; set; }
        public int Корабль { get; set; }
        public System.DateTime Дата_учения { get; set; }
        public string Место_проведения { get; set; }
        public int Оценка { get; set; }
    
        public virtual Корабли Корабли { get; set; }
        public virtual Части Части { get; set; }
    }
}
